alias dcps="docker-compose ps "
alias dcup="docker-compose up -d "
alias dcstop="docker-compose stop "
alias dcrestart="docker-compose restart "
alias dcdown="docker-compose down "
alias dcbuild="docker-compose build "
